### ISSUE TITLE
Develop BACnet tests

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#109]
The BACnet tests will include:

bacnet.version #132 
bacnet.addr_unique #131 
bacnet.pic #130 
bacnet.compliance #129

**Comment by ewRedstone** [comment]
I've started BACnet discovery for device endpoints.

I am now developing towards BACnet points inside device endpoints.

**Comment by pisuke** [comment]
BACnet device and endpoints scans included in [bacnet4j update](https://github.com/grafnu/bacnet4j/pull/1).

**Comment by grafnu** [comment]
I'd be curious to know how you expect to implement the "addr_unique" test, since it's impossible to do for a single device under test (since you need to have the complete set of devices to know if any given address is unique).

**Comment by aidanparkinson** [comment]
@ewRedstone please make pull request for BACnet tests developed so far.

**Comment by ewRedstone** [comment]
https://github.com/grafnu/bacnet4j/pull/2

**Comment by InBrewJ** [comment]
ss by #132 #129 #130 #131
