### ISSUE TITLE
Develop dhcp.long test

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#111]
SUGGESTED IMPLEMENTATION:
Use the misc/increase_leastime script to enable a longer DHCP lease.

VALIDATION:
Check with tcpdump that a DHCPREQUEST message is sent by the device after the lease has expired.

**Comment by ewRedstone** [comment]
https://github.com/arupiot/daq/pull/14

**Comment by pisuke** [comment]
Closing as test is no longer in test plan.
