### ISSUE TITLE
Soak test reporting feature

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#118]
This feature enhancement is to enable the reporting of the outcome of multiple tests which have run on DAQ for a long time (hour, day, week).

Would it be possible to have a module that at a specific time (after 1 hour, after 1 day, after 1 week) parses all the test results files and finds errors/test failures? 
This could also be posted to the Firebase dashboard as an additional test line.

**Comment by grafnu** [comment]
I'm not sure what to say as it's a fairly non-specific request. Can you distill it down to a specific example of what this might look like?   Just a sample of what a soak test report might look like?

**Comment by pisuke** [comment]
OK, here is an example.

** Module Soak

*** Soak test - 1 hour

| Number of DAQ runs |   19  |
|--------------------|-------|
| PASS               |   17  |
| FAIL               |    1  |
| WARN               |    1  |

```
FAIL

2019-05-28 12:32 nmap
[ last 
      # lines
        of relevant
           test 
              output]
```

```
WARN
2019-05-28 12:54 nmap
[ last 
      # lines
        of relevant
           test 
              output]
```

*** Soak test - 1 day

| Number of DAQ runs |   450 |
|--------------------|-------|
| PASS               |   448 |
| FAIL               |     1 |
| WARN               |     1 |

```
FAIL

2019-05-28 12:32 nmap
[ last 
      # lines
        of relevant
           test 
              output]
```

```
WARN

2019-05-28 12:54 nmap
[ last 
      # lines
        of relevant
           test 
              output]
```

Soak test - 1 week

| Number of DAQ runs |   3190 |
|--------------------|-------|
| PASS               |   3188 |
| FAIL               |     1 |
| WARN               |     1 |

```
FAIL

2019-05-28 12:32 nmap
[ last 
      # lines
        of relevant
           test 
              output]
```

```
WARN

2019-05-28 12:54 nmap
[ last 
      # lines
        of relevant
           test 
              output]
```

**Comment by grafnu** [comment]
Good example, and discussed, there's two parts I don't understand...

1) What does "relevant" mean?  That's a subjective call, so we need to distill it down to an objective thing that can be automated by the tool.
2) What happens when there's 200 warnings? I don't think this format will scale very well.

I think a format that is more of a table (tests on one axis, and then various runs on the other) -- and then if somebody wants to know more they can go look at the relevant offending report?  This is more or less how the current web-ui is setup. (I know you want something static like a .md file, which is fine -- I meant about the general structure/format of that)

**Comment by pisuke** [comment]
Resurrecting this issue.
The soak testing feature that allows to see the full test report history is no longer appearing, so possibly broken in the firebase UI. Can this be fixed?
On this note, is it possible to discuss how the test report history can be made persistent?
At the moment when DAQ is restarted, all the history is lost.

**Comment by pisuke** [comment]
Hi Trevor, i cannot get the test report history (soak testing feature) to show up when running DAQ with cmd/run. I have a working physical switch setup with the web UI, but when I click on the port-# link there is a page with the header. See attached screenshots below.

<img width="1412" alt="Screen Shot 2019-06-11 at 18 41 12" src="https://user-images.githubusercontent.com/1533891/59294099-882b1600-8c78-11e9-9707-14494c6e22bc.png">
<img width="898" alt="Screen Shot 2019-06-11 at 18 41 20" src="https://user-images.githubusercontent.com/1533891/59294100-88c3ac80-8c78-11e9-8cee-fe2d0833dd44.png">

Can you please take a look?

**Comment by grafnu** [comment]
This should be fixed. The history page should be back now!  It will require a redeploy of the Firebase code.

**Comment by pisuke** [comment]
Great, thank you! Just did a rebuild and all worked nicely. :-)
I'll test this feature on Monday and send some feedback and ideas on how it fits with a soak testing workflow for individual device testing.
