### ISSUE TITLE
`sudo bin/setup_base` does not install openvswitch on Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by InBrewJ** [faucetsdn/daq#119]
Running `sudo bin/setup_base` results in the following output:

> AG is sudo apt-get -qqy --no-install-recommends
E: Package 'realpath' has no installation candidate
Installing for ubuntu bionic
deb http://packages.wand.net.nz bionic main
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2221  100  2221    0     0   4105      0 --:--:-- --:--:-- --:--:--  4105
OK
Hit:1 http://ppa.launchpad.net/videolan/master-daily/ubuntu bionic InRelease
Hit:2 http://gb.archive.ubuntu.com/ubuntu bionic InRelease                        
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]       
Ign:4 http://dl.google.com/linux/chrome/deb stable InRelease                      
Hit:5 http://gb.archive.ubuntu.com/ubuntu bionic-updates InRelease                
Hit:6 http://packages.microsoft.com/repos/vscode stable InRelease                 
Hit:7 https://download.docker.com/linux/ubuntu bionic InRelease                   
Hit:8 http://ppa.launchpad.net/wireshark-dev/stable/ubuntu bionic InRelease       
Get:9 http://gb.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]    
Hit:10 https://dl.yarnpkg.com/debian stable InRelease                             
Hit:11 http://dl.google.com/linux/chrome/deb stable Release                       
Hit:12 http://packages.cloud.google.com/apt cloud-sdk-bionic InRelease            
Hit:13 http://packages.wand.net.nz bionic InRelease                               
Fetched 163 kB in 1s (185 kB/s)                    
Reading package lists... Done
E: Packages were downgraded and -y was used without --allow-downgrades.

as a result, `sudo apt-get install openvswitch-switch openvswitch-common` is never run and when tests are executed daq fails.

Workaround: run `sudo apt-get install openvswitch-switch openvswitch-common` manually

**Comment by grafnu** [comment]
Thanks for the great bug report. I'm not sure what to do with it though, since I think it has to do with your local system setup. I ran it on a new Ubuntu 18.04 LTS image, and the package list is different than yours. You have 13 entries, I only have 9.  Was there any information on what the conflicting package was?  I'm hesitant to add the "--allow-downgrades" option because I fear it might break existing installs. What base Ubuntu image were you starting from?

```
Hit:1 http://us-west1.gce.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://us-west1.gce.archive.ubuntu.com/ubuntu bionic-updates InRelease                
Hit:3 http://us-west1.gce.archive.ubuntu.com/ubuntu bionic-backports InRelease              
Get:4 https://download.docker.com/linux/ubuntu bionic InRelease [64.4 kB]                   
Hit:5 http://archive.canonical.com/ubuntu bionic InRelease                                  
Hit:6 http://security.ubuntu.com/ubuntu bionic-security InRelease                           
Get:7 https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages [5673 B]        
Get:8 http://packages.wand.net.nz bionic InRelease [13.5 kB]                                
Get:9 http://packages.wand.net.nz bionic/main amd64 Packages [68.0 kB]
```

**Comment by jhughesbiot** [comment]
I am experiencing this same issue.  

To prevent breaking existing installs, would it be possible to add the --allow-downgrades as a parameter to the binary for those encountering this issue?  Or better maybe still, remove  -y as the default behavior and make -y an acceptable parameter to the binary?  This would allow finer control of the package installs on a per installation basis still allowing current behavior by supplying -y and removing it would allow users experiencing downgrade issues access to the messaging behind that conflict for resolution.

**Comment by grafnu** [comment]
Sure, why don't we give it a try?  Can you put together a PR for it and
then either I or Francesco could review... good time to practice me not
being around :-).
