### ISSUE TITLE
Add summary of manual tests results in the report

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#124]

**Comment by pisuke** [comment]
The report needs tidying up by including the following recommendations from Clare and Louis.

These should really be separate issues in the Kanban, just putting them temporarily in one issue.

Reinstate device summary

Report summary needs a conclusion "Device Passed Automated Tests", "Device Failed Automated Tests"

Title should state the manufacturer and model number

Include firmware version, possibly take it directly from device (bacnet scan, nmap scan or other methodology)

Reports generating twice, 1 showing half of the information from the test and the other is a full report

Warning: Should NOT have additional property: process' - Process is there to show No of times the device has been tested on the DAQ report

Warning: Should be string' - WebUI showing this warning error when it is already a string? Example Serial Number/Version

Report history won't appear when clicking on the port in the WebUI

When the module_config.json file is edited manually, in order to refresh in the GUI, DAQ has to be restarted

Module tls: asks about v3 and v4, where we had manually been testing v1.2 (required), v1.3 (recommended) and EAP-TLS (recommended). Clarify.

pull the Compliance category Result section to between Device description and Device documentation

**Comment by noursaidi** [comment]
@pisuke I've made a PR #481 which implements the test in the method you've mentioned.

The only improvement which has just occurred to me is I think the manual tests might need an enforced expiry or timestamp as module_configs might linger for a while with the manual test results
