### ISSUE TITLE
Develop security.passwords test

### ISSUE THREAD

**Issue by InBrewJ** [faucetsdn/daq#128]

**Comment by InBrewJ** [comment]
@ktredstone preface each commit with faucetsdn#128

**Comment by ewRedstone** [comment]
password test for ssh has been completed. test requires telnet for some unknown reason as telnet not a valid protocol on a google network.
Test also requires https login ? need to investigate further methdoology for scraping and brute force password hacking web pages that could be written in various langauges such as( php, asp.net, nodeJS. java, Spring etc.....)
