### ISSUE TITLE
Develop bacnet.compliance test

### ISSUE THREAD

**Issue by InBrewJ** [faucetsdn/daq#129]

**Comment by ewRedstone** [comment]
Awaiting since 02/04/2019 (ARUP) Francesco Anselmo to define Google MEP Bacnet compliance for each component AHU, PUMP, FCU, BOILER etc. Bacnet Values e.g. COV, min send, max send, min present value, max present value, etc

**Comment by pisuke** [comment]
I understand that this action is now with Oli.

**Comment by ewRedstone** [comment]
The team collectively is still unable to define a definitve answer of what BACnet compliance is

**Comment by pisuke** [comment]
Closing as out of date.
