### ISSUE TITLE
Develop bacnet.addr_unique test

### ISSUE THREAD

**Issue by InBrewJ** [faucetsdn/daq#131]

**Comment by aidanparkinson** [comment]
Being addressed in pull request [https://github.com/grafnu/daq/pull/137](url)

**Comment by ewRedstone** [comment]
this is blocked due to a test container only being able to communicate with the faux device it is aligned with. Unable to test across multiple faux devices from a single test

**Comment by ewRedstone** [comment]
https://github.com/faucetsdn/daq/issues/186

**Comment by pisuke** [comment]
Closed as test no longer in test plan.
