### ISSUE TITLE
Overall FAIL/PASS test result

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#133]
Report summary needs a conclusion "Device Passed Automated Tests", "Device Failed Automated Tests".

**Comment by grafnu** [comment]
What's the logic behind the result?  Is it sufficient to say "no required tests fail"?

**Comment by pisuke** [comment]
Yes, it is sufficient. 
The logic is:
if no required tests fail, then show an overall pass.

**Comment by pisuke** [comment]
Addressed in grafnu/daq#170
