### ISSUE TITLE
Device make and model number in report title

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#134]
Title should state the manufacturer/make and model number

**Comment by grafnu** [comment]
Fixing with https://github.com/grafnu/daq/pull/150

**Comment by pisuke** [comment]
Title to be:

Device ***MAC_address***, ***Make*** ***Model***

**Comment by pisuke** [comment]
Addressed in [grafnu#172](https://github.com/grafnu/daq/pull/172)
