### ISSUE TITLE
Automatic scan of firmware version

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#135]
At the moment the report templating allows to include the firmware version manually, but it is possible to derive this value programmatically using nmap scripts for BACnet and zeroconf/mDNS.
https://nmap.org/nsedoc/scripts/bacnet-info.html
https://nmap.org/nsedoc/scripts/dns-service-discovery.html
This could either be a framework or test development addition. Any advice, comments?

**Comment by grafnu** [comment]
This would be a test module, not framework addition.

**Comment by pisuke** [comment]
OK, moving this to test development and reassigning to Redstone.

**Comment by pisuke** [comment]
@InBrewJ 

The test should be formatted so that it can be used as a template for other tests.
It should include these variables"

TEST_NAME = testcategory.testname
TEST_DESCRIPTION = "A description of the test to give context about what it is doing. The test passes if this condition is met. The test fails if this condition is met. Or the test if for information only"

The output of the test in the modules section should be 

--------------------
$TEST_NAME
--------------------
$TEST_DESCRIPTION
--------------------
$LOG

There should be a clear identification of the skip, pass, fail and info cases (where applicable).
The skip case is if the test is either not applicable or user disabled.

The result should be something like this:

RESULT pass testcategory.testname Indicative text with summary of result or useful information.

**Comment by InBrewJ** [comment]
Conditions for security.firmware:

pass -> version **matches** device_info.firmware_version
fail -> version **DOES NOT match** device_info.firmware_version
info -> version found from device but none defined in device_info.firmware_version
skip -> cannot get firmware version from device, ports may be filtered (as with the EasyIO case)

Conditions for security.dns:
info -> services discovered
