### ISSUE TITLE
Add test categories and status summaries to report

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#139]
Add compliance category result summary section to between Device description and Device documentation.

**Comment by pisuke** [comment]
This needs a clear definition as it has implications on the framework.

**Comment by pisuke** [comment]
For each test inside each module we need a functionality for the DAQ test operator to define whether the result of the test is "required pass" or "recommended pass" and a category it is assigned to (for instance "compliant" or "smart enabled").

Once DAQ has run all the tests, it then creates two summaries:

1. A total FAIL/PASS result against the categories

2. A summary of how many tests in each category have passed or failed

**Comment by pisuke** [comment]
@grafnu the test category should be added by the test operator in the system module_config.json.
For instance this file could look like this with the added subtests selection:

{
  "modules": {
    "tls": {
      "enabled": true,
      "tests": {
         "skip security.tls.v3": "required",
         "skip security.x509": "recommended"
      }
    }
  }
}

I can work on defining the exact template/example for this if the approach is correct.

**Comment by grafnu** [comment]
I think the tests should be abstracted away from the modules, so it would
be something more like:
{
  "tests": {
    "security.tls.v3": {
           "result": "required"
     }
   }
}

Or something like that. Not generally a good idea to try and smash fields
together ("skip security.tls.v3") -- so want to find the right structured
way to represent the needful.  I ca

**Comment by pisuke** [comment]
Yes, sorry, that was my bad copy&paste!
I'll do a pass on it tomorrow. Thanks for having a look!

**Comment by pisuke** [comment]
@grafnu sorry it took a bit longer than anticipated!

Here is a mock up of a portion of the device or device_types module_config.json with the test information/selection enhancements.

{
 "modules": {
   "bacext": {
     "enabled": true
   },
 },
  "tests": {
    "security.tls.v3": {
           "description": "Verify the device supports TLS 1.2 or above as a client",
           "enabled": true,
           "result": "required",
           "type": "automatic"
     },
    "manual.wireless_ap_disabled": {
           "description": "Verify that the devices is configured not to act as an access point and not to have any hidden SSID",
           "enabled": true,
           "result": "required",
           "type": "manual"
     }
   }
}

I've also included a "manual" test object for completeness, to demonstrate this functionality can be used to address also #124.

I can generate a template including all current tests if you need one.

**Comment by pisuke** [comment]
Addressed in [grafnu#170](https://github.com/grafnu/daq/pull/170)
