### ISSUE TITLE
Add test description for each test in test report summary.

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#145]

**Comment by pisuke** [comment]
This feature request is to add a column in the test report summary that includes a description of each tests.
The description of each test is written by the test developer and included both in the test report summary and in the first line of each test diagnostic output.

**Comment by grafnu** [comment]
This is conflating tests and modules. For tests (base.target.ping) this is already there -- the word "target" is just text that's included in the summary table -- if you want this could be the description. For modules (which I think is what you mean by test diagnostic output) -- that's simply the output of the test so if you want a description there then the test just needs to output it.

If you mean something else, then a concrete example of what this would look like in a modified device_report.md would be required.

**Comment by pisuke** [comment]
Closing this very old issue, all new and old tests now have readme descriptions and test output descriptions.
