### ISSUE TITLE
bin/setup_daq is cloning faucet from the wrong github account

### ISSUE THREAD

**Issue by JoelRedstone** [faucetsdn/daq#150]
When running bin/setup_daq or bin/setup_dev daq is cloning faucet from my personal github repo asking me to insert my username and password. The cloning and the overall setup fails if faucet is not present. Below are the logs:

Cloning https://github.com/JoelRedstone/faucet...
Cloning into 'faucet'...
Username for 'https://github.com': joelredstone
Password for 'https://joelredstone@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/JoelRedstone/faucet/' not found

@grafnu

**Comment by grafnu** [comment]
Whoops. Reverted change. This should be back to previous in grafnu/master and faucetsdn/master

```
~/daq$ git log -n 1
commit b1e16875d282e4112543a0f2990cf5d7f7621b7f (HEAD -> master, origin/master, origin/HEAD, faucet/master)
Author: Trevor Pering <peringknife@google.com>
Date:   Fri Jun 21 04:57:16 2019 -0700

    Revert faucet repo autodetect
```
