### ISSUE TITLE
examples and configs need updating

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/daq#153]
Example files should use "servers" instead of "ports" and nmap schema, as per ./misc/test_site/mac_addrs/9a02571e8f01/module_config.json (correct example)

bad places to check:

./firebase/public/schema_device.json
./qualification/device_module_config.json
./misc/test_site/mac_addrs/9a02571e8f02/module_config.json

**Comment by pisuke** [comment]
Addressed in [grafnu#164](https://github.com/grafnu/daq/pull/164)

**Comment by pisuke** [comment]
Merged
