### ISSUE TITLE
cannot name a folder aux, reserved by windows OS

### ISSUE THREAD

**Issue by ewRedstone** [faucetsdn/daq#154]
daq/misc/test_site/device_types/rocket/aux/

this folder doesnt work with windows development setups due to aux being reserved by windows OS
basically this did work previously and now doesnt work

**Comment by ewRedstone** [comment]
this impacts development of subset modules on a windows box

**Comment by pisuke** [comment]
closing this as DAQ is not intended to be developed on windows
