### ISSUE TITLE
Explanatory notes in device reports

### ISSUE THREAD

**Issue by aidanparkinson** [faucetsdn/daq#172]
There are a number of tests that do not print short explanatory notes in the markdown device reports for test outcomes. These tests include all those in the `connection` and `poe` modules. Please can we ensure that all tests print a short explanatory note of why the test has reached a given outcome. See screenshot for details:

<img width="686" alt="Screenshot 2019-08-08 at 09 19 25" src="https://user-images.githubusercontent.com/48984049/62686973-b51c5080-b9bd-11e9-81a3-4fd51c8e179e.png">

**Comment by ewRedstone** [comment]
This notes column has only just been introduced on the arupiot fork, this has yet to be accepted by Trevor and also Faucet.

Please can you identify from the current report what data should be in the notes column for each test.

We have plenty of data, identifying what data is more important needs to be defined by a consultant

**Comment by pisuke** [comment]
This has been progressed to some degree but there are still tests not outputting short summaries:
* `mac_oui`
* all the switch tests

**Comment by pisuke** [comment]
@OzyOzk do you have an update on this?

**Comment by OzyOzk** [comment]
@pisuke I'm still working on this one. I'm aiming to finish it by the end of the week.

**Comment by pisuke** [comment]
Thanks @OzyOzk make sure the full Travis process is also included. This means ensuring that report and output files are synced with the code changes.

**Comment by pisuke** [comment]
@noursaidi can you please do review on the full test code base inside /subset to check which tests don't output any information in the summary for the pass/skip/fail/info steps?
Having a table here for discussion would be useful.

**Comment by noursaidi** [comment]
@pisuke it looks like only the certificate (TLS/x509) tests currently produce a summary note, but they do produce output useful information. In PR #412 I've copied this information into the summary table. The options are as follows. Should we have the certificate expiry date/start date with the respective notes?
| Result | Note
| - | --- |
| Skip | "MalformedURLException unable to connect to server. |
| Skip | IOException unable to connect to server |
| Fail | Unknown certificate type |
| Fail | Certificate not yet valid. |
| Fail | Certificate is expired. |
| Pass | Certificate is active for current date. |


BACnet summary notes adressed in #386

**Comment by pisuke** [comment]
@noursaidi I think @jhughesbiot was working on the TLS tests in #362 which has now been approved and should be merged soon. Can you please coordinate?

**Comment by jhughesbiot** [comment]
@noursaidi 
I can see the messages you're referring to are still missing from https://github.com/faucetsdn/daq/pull/362.  The validation of a cert is now more involved than just the expiration date but I will do a quick update to that PR to add appropriate messages to the status of the certificate.

**Comment by jhughesbiot** [comment]
Updated to account for the multiple failure points and messaging. This is from the test_modules output to show the new messaging.

```
Testing tls alt
RESULT skip security.tls.v1 IOException unable to connect to server
RESULT skip security.tls.v1.x509 IOException unable to connect to server
RESULT skip security.tls.v1_2 IOException unable to connect to server
RESULT skip security.tls.v1_2.x509 IOException unable to connect to server
RESULT skip security.tls.v1_3 IOException unable to connect to server
RESULT skip security.tls.v1_3.x509 IOException unable to connect to server
Testing tls alt tls
RESULT pass security.tls.v1 Certificate active for current date and public key length > 2048.
RESULT pass security.tls.v1.x509 Certificate active for current date and public key length > 2048.
RESULT pass security.tls.v1_2 Certificate active for current date and public key length > 2048.
RESULT pass security.tls.v1_2.x509 Certificate active for current date and public key length > 2048.
RESULT pass security.tls.v1_3 Certificate active for current date and public key length > 2048.
RESULT pass security.tls.v1_3.x509 Certificate active for current date and public key length > 2048.
Testing tls alt expiredtls
RESULT fail security.tls.v1 Certificate is expired.
RESULT fail security.tls.v1.x509 Certificate is expired.
RESULT fail security.tls.v1_2 Certificate is expired.
RESULT fail security.tls.v1_2.x509 Certificate is expired.
RESULT fail security.tls.v1_3 Certificate could not be validated.
RESULT fail security.tls.v1_3.x509 Certificate could not be validated.

```
