### ISSUE TITLE
poe.negotiation invalid test result

### ISSUE THREAD

**Issue by aidanparkinson** [faucetsdn/daq#190]
The poe.negotiation test does not return valid test results to meet the functional requirement.

Please implement the following test procedure and re-submit:

Use the switch command "show power-inline interface port#.#.##" to verify that the port is configured to negotiate power {Admin = "Enabled"}

**Comment by ewRedstone** [comment]
@aidanparkinson  addressed in https://github.com/arupiot/daq/pull/15
