### ISSUE TITLE
poe.power invalid test results

### ISSUE THREAD

**Issue by aidanparkinson** [faucetsdn/daq#191]
The poe.power test does not return valid test results to meet the functional requirement.

Please implement the following test procedure and re-submit:

Use the switch command "show power-inline interface port#.#.##" and return test result "fail" if either of the following states are TRUE: {Oper = "Fault", power>Max}

**Comment by ewRedstone** [comment]
@aidanparkinson addressed in https://github.com/arupiot/daq/pull/15
