### ISSUE TITLE
refactor switch tests

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#194]
output to a separate report text file for each test
add enums for arrays to make code more readable
add description for each test

**Comment by InBrewJ** [comment]
@pisuke I made a start on this one [here](https://github.com/arupiot/daq/tree/reformat_report_switch)

The main addition is the [module_manifest.json](https://github.com/arupiot/daq/blob/reformat_report_switch/subset/switches/module_manifest.json) file in the switch folder from which we get the descriptions. With that, we can edit the descriptions of each test without touching the Java and also pave the way for some autogenerated documentation. At the moment this produces a skip result like this:

https://firebasestorage.googleapis.com/v0/b/arup-bos.appspot.com/o/inst%2Freports%2Freport_9a02571e8f02_2019-09-23T162652%2B0000.md?alt=media&token=f48bb71c-6ccd-43b9-ad11-6046f3e3a6ec
