### ISSUE TITLE
Investigate linting the markdown report for, e.g. column width < 80

### ISSUE THREAD

**Issue by InBrewJ** [faucetsdn/daq#208]

**Comment by InBrewJ** [comment]
@pisuke For this, we could use something heavyweight like:

- https://prettier.io/
- https://github.com/remarkjs/remark-lint#using-remark-to-fix-your-markdown
- etc

This is fine and offers the most flexibility but most of these sorts of applications run on top of node which means that node/packages and *all of its/their transitive dependences* would have to be included just to lint markdown

Or, we could use `fold`, something like: https://unix.stackexchange.com/questions/25173/how-can-i-wrap-text-at-a-certain-column-size

Which wouild be something like:

`fold -w 80 -s report_3c5ab41e8f0a_2019-10-08T135028+0000.md > formatted.md`

at an opportune place in DAQ.

For a full report, a fold produces something like this:

**Comment by pisuke** [comment]
`fold` looks good enough for now, thanks for looking into it!
