### ISSUE TITLE
security.ports.nmap: invalid faux device test results

### ISSUE THREAD

**Issue by aidanparkinson** [faucetsdn/daq#209]
When running /testing/test_aux.sh:
- Device testing reports inconsistent results between faux devices ("pass/fail") when identifying port 443 open.
- Device testing reports BACnet ports is currently out of the coverage of the nmap port scan (BACnet ports not identified as open).

Is there an (unknown to me) justification for this behaviour? This needs an explanation.

**Comment by InBrewJ** [comment]
@aidanparkinson I'll open a branch trying the nmap `-p-` option. At the moment the command that nmap runs is:

`nmap -v -n -Pn -T4 --open -oG $LOG $TARGET_IP`

which may or may not scan all ports, I'll look into it...
