### ISSUE TITLE
security.password.[x] exception handling

### ISSUE THREAD

**Issue by aidanparkinson** [faucetsdn/daq#215]
Line 59 `~/daq/subset/security/security_passwords/src/main/java/setupTest.java` reads `"RESULT skip security.passwords." + protocol + "mac address not found in defaultPasswords.json"`, which is correct in the case of an exception due to `connection.macoui` skip/fail results, but not if the mac address is not found in `defaultPasswords.json` - this line needs to be replaced with two separate exception rules for these different cases.

**Comment by pisuke** [comment]
@OzyOzk is this still a current issue?

**Comment by OzyOzk** [comment]
This issue has already been resolved. The existence of the mac address in the default credentials file is checked on line 43 of subset/security/security_passwords/src/main/java/TestPassword.java

`   if (macIsInCredentialsFile && desiredPortOpen) {
        DefaultCredentials.writeUsernamesToFile(mac, protocol);
        DefaultCredentials.writePasswordsToFile(mac, protocol);
`

**Comment by aidan-parkinson** [comment]
Looking at the code now, I'm not sure my original comment is relevant anymore. I believe that a missing mac address entry in `defaultPasswords.json` would generate the following error: `"RESULT skip security.passwords.%s Could not lookup password info for mac-key: %s\n"`. This could be acceptable.

Probably an idea to close this issue and to functionally test for witnessing again?

**Comment by pisuke** [comment]
Sounds good, closing it out for now and testing it all again. Thanks both!
