### ISSUE TITLE
Rename tests according to test plan v 3.6

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#226]

**Comment by OzyOzk** [comment]
I made the changes on the fork below.

https://github.com/OzyOzk/daq

**Comment by pisuke** [comment]
@OzyOzk you must always create branches on your fork when working on an issue. Please refer the issue number in the name of your branch. Can you also merge from upstream please as many things have changed over the past week? Thanks.

**Comment by pisuke** [comment]
Addressed in #682
