### ISSUE TITLE
Remove brute test from list of tests

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#236]
@grafnu I'd like to remove the brute test from the list of tests.
It is a confusing test to be there, as it has been done for demonstration purposes and doesn't do anything useful.
Just checking with you it's OK before proceeding.

**Comment by pisuke** [comment]
Hi @grafnu, any thought on this?

**Comment by grafnu** [comment]
Fine by me... It's not really a framework feature, so really is up to
policy.

**Comment by pisuke** [comment]
Thanks Trevor, OK we'll proceed then. 
Hi @OzyOzk this is a good one for you to start familiarising with the test development process. I'm assigning it to you.
