### ISSUE TITLE
fix security.passwords test

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#237]

**Comment by henry54809** [comment]
Hey Francesco, 
Haoli here. Are you actively working on making telnet test less flaky?

**Comment by pisuke** [comment]
Ciao Haoli, I haven't started yet, so good to coordinate. 
I need to have a better look at the code, but happy for you to lead on this if you've already started.

**Comment by pisuke** [comment]
Hi @henry54809 comments? or can I start having a look?

**Comment by henry54809** [comment]
I've made a fix at https://github.com/faucetsdn/daq/pull/240 It's as best as I could make it. @pisuke

**Comment by pisuke** [comment]
Thanks Haoli, I'll check it out. Closing this issue for now then.
