### ISSUE TITLE
Validate completed tests from RS

### ISSUE THREAD

**Issue by spectre-storm** [faucetsdn/daq#244]

**Comment by OzyOzk** [comment]
Can we link the fork/branch that these tests were developed on. There's multiple RS forks.

**Comment by pisuke** [comment]
Difficult to do now, I think we just execute the tests on faux and real device to check how the functionally behave. 
The validation process includes executing the tests and generating report for fail, pass and skip cases. 
For reference, here is a report and relevant configuration for a device: 
[DAQ_test_results.zip](https://github.com/faucetsdn/daq/files/4376148/DAQ_test_results.zip)
I'm half through this process and I'll detail the results of the validation process in this issue.

**Comment by spectre-storm** [comment]
We will close this issue and create smaller / specific issue depending on which Tests to validate
