### ISSUE TITLE
remove docker_images.txt from misc folder

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#250]

**Comment by pisuke** [comment]
@grafnu should the misc/docker_images.txt file be added to .gitignore?

**Comment by grafnu** [comment]
No. Do not do this.

**Comment by pisuke** [comment]
Thanks, understood it's the wrong way to address this.
For context, because this file is in a folder tracked by git, and because it changes at every build in a machine/daq instance dependent way, I don't think it is appropriate to keep it in this folder.
Can the file be somewhere else appropriate, or not be generated at all?

**Comment by grafnu** [comment]
I think for now it should be generated maybe into the inst folder since
it's a parameter of this instance...
