### ISSUE TITLE
development branch needed

### ISSUE THREAD

**Issue by jhughesbiot** [faucetsdn/daq#251]
Since we are now creating pull requests directly to this repo instead of grafnu, we need a develop branch that should be created to keep code changes directly to master.  The grafnu repo acted like a development branch until now so we should make sure we have that going forwarad.

**Comment by pisuke** [comment]
Hi @grafnu not sure what you think about this, as I know you're working on setting up a release cycle. Up to know we've been just working with pull requests which has been OK, but @jhughesbiot is suggesting using a dev branch. Thoughts?

**Comment by grafnu** [comment]
The reason we had grafnu before was b/c permissions, and who could approve
PRs, but that's been resolved now so the appropriate people should be able
to do a PR against faucetsdn/daq. We're generally following the GitHub Flow
model <https://guides.github.com/introduction/flow/>.  Specifically, then,
all dev work would be done in your own fork on your own branch, and then a
PR is made against faucetsdn/master -- once that's approved/submitted, then
we're done and all good.

Releases are tags applied to the branch.  There is no separate release
branch.  Given the way git works, a tag is semantically equivalent to a
branch -- it just doesn't move.

**Comment by pisuke** [comment]
Thanks Trevor, closing this issue then as all clear. @jhughesbiot no need for development branch because using the [GitHub Flow Model](https://guides.github.com/introduction/flow/).
