### ISSUE TITLE
Subdivide test_aux.sh and test_base.sh into smaller chunks.

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#253]
Subdividing test_aux.sh and test_base.sh into smaller chunks would help with getting the testing cycle quicker. 
@grafnu is this something we can work on?
I understand that there is a dependency with Travis so seeking your advice.

**Comment by grafnu** [comment]
Good in theory, but it's not always a win like you'd expect. There's a significant starutp-cost for each container, so simply splitting them can make things worse in terms of overall testing.

What exactly about the "testing cycle" are you trying to improve?  If you're doing a development testing cycle while actively working on tests then there's plenty of ways to speed that up without futzing with the overall system.  Can you give an example of what kind of development you mean?  E.g., "When I change subset/cloud/test_udmi I want to be able to run the effected travis test quickly?"

**Comment by jhughesbiot** [comment]
From what I've seen, the cost of startup is more about the building of the docker images that occurs on each boot.  Maybe there should be a "local" flag added to the test scripts which would use local docker images rather than rebuilding.  This would mean you have to build your specific test module manually but that could at least speed up some of this testing and a minimal extra step to developing.

I think the your comment about the testing cycle is spot on.  Having a way to test just the changes in a specific module with the effect result to what travis will do is the real goal.

**Comment by grafnu** [comment]
It sounds like you're trying to bend the integration test suite in the
wrong direction. testing/test_aux.sh was never intended to do what you're
trying to use it for. It's job is to run the entire test integration suite,
not tuned for local development.  If you're trying to iterate and develop a
specific test, then I strongly suggest you just setup your system how you
need it, and then run the commands you need, rather they trying to run
everything and/or whittle it down.

If your goal is to iterate on the TLS tests, then just setup for that:

   1. What devices do you need/want?  Do you just need one?  Three? What
   parameters?
   2. What tests do you need to run?  No need to run them all if you only
   care about TLS.
   3. Then just do "cmd/run -s" to do a test run.

Waaayyyy quicker than trying to run testing/test_aux.sh and narrowing it
down. This bit of code shows a starting point for constructing the
configuration
<https://github.com/faucetsdn/daq/blob/master/testing/test_aux.sh#L49>.

Once you're done developing, then you go back and fiddle with test_aux.sh
to have the full integration test in place... but that's not development
anymore.

**Comment by jhughesbiot** [comment]
Your questions show the issue actually.  If somebody modified a test to do a something different, they don't necessarily know what all the devices are configured for in the aux test but they are forced to have that knowledge.  Without knowing what is expected for every single device for every single test that will be run in test_aux, they can't fix the text_aux.out file and so travis will fail even if the test itself is fine.

**Comment by grafnu** [comment]
I don't understand what you're saying. Having complete knowledge of the
system is nearly impossible, but I don't see why you think somebody is
forced to have that knowledge. The only place it's really intended to be
captured is the complete integration test suite ("if it's not tested, then
it doesn't exist") -- but that's not something somebody is supposed to have
in their mind.  This model is fairly typical for many software systems out
there that follow a CI/TDD methodology, not something specific to DAQ. For
a developer, the trick is to narrow the scope to what you're trying to
change/test, and then rely on the integration tests to make sure you're not
breaking something else.  I don't see why this philosophy doesn't apply in
your case with TLS.  You don't rely on the integration tests for your TDD
workflow.

**Comment by jhughesbiot** [comment]
Here's a scenario to help illustrate why you need knowledge of the system to accurately write tests for the integration tests to pass and why it's critical to be able to emulate as close as possible to the travis tests for sanity checks before waiting an hour+ for it to pass/fail in the CI.

Device A is started with configuration B to run on Port C.  This tells Device A to have a passing result for TLS 1.2.  A test is written to test TLS 1.2 and gets a failure result when tested against this device.  Not knowing anything about Device A, you assume the test results are correct and update test_aux.out is to reflect a failure result as the expected result.  The CI passes its build because it matches.  In the field, good devices that support 1.2 are now being failed because the TLS tests is flawed.  

In the same way, the opposite could be true. A device could report success when it shouldn't because of some edge case not detected in the test but because you don't know anything about the devices and their configurations, you can't validate the results only update the expected results to pass the CI.

**Comment by grafnu** [comment]
Still sounds to me like you're conflating a test development workflow with
CI integration testing.

CI integration testing is meant to be comprehensive. Speed is not a primary
consideration. It serves a different function than development.

For development of TLS, I would configure the system to run the tls test
just against the three cases { skip, pass, fail }, e.g. using the settings
below (tail end of a system.conf configuration). Then just run with
"cmd/run -b -s" -- no need for test_aux.sh at all.

# Command file with startup commands.
startup_faux_1_opts=""
startup_faux_2_opts="expiredtls"
startup_faux_3_opts="tls"
startup_cmds=misc/startup_multi.cmd

# Only run a few tests
host_tests=subset/security/build.conf

Why is that not sufficient to develop the TLS test?  I timed it and the
run took ~2.5 min. Why is all the other stuff in test_aux.sh necessary?
Just with this config (in local/) -- you can then occasionally push to
GitHub and test through travis... but that's not a development loop, that's
just for catch-all things like unintended breakage of other things and/or
lint testing.

**Comment by pisuke** [comment]
Just to summarise the discussion, there are two types of tests to "test the tests" that need to be written:

1) Functional tests, which are down to the DAQ test developer to write. They can just be configuration files and could be stored in the subset/foldername/ folder or wherever practical, even be ephemeral, but perhaps a good idea to keep them in the subset/ folders.
Functional tests are to make sure that the device tests work properly.

2) Integration tests, which are down to the DAQ framework developer to write and occasionally for the DAQ test developer to tweak.
Integration tests are to make sure that new code doesn't break old one and that different functional units integrated in the code work together without causing issues.

**Comment by grafnu** [comment]
I don't think this is quite right.

*Functional tests*: There are test modules,
like subset/network/Dockerfile.test_network which is a module that is run
by the framework. This module, when executed, is given a target IP address
and does the needful to generate a report.  I'm not sure what you mean by
"can just be configuration files" -- there definitely needs to be some code
in there that does something. The functional tests are there to test a
specific piece of functionality, given a DUT. Except for base
functionality, these should be in the appropriate subset/ folders. These
are there to test specific functionality of a device (real or faux) to make
sure that the DUT is behaving properly.

*Integration Tests* take individual test modules and apply them together in
a test suite that checks "everything" integrated together. When writing a
test module, the developer also needs to be adding them into the
integration test suite to be tested under CI. These are run against the
faux device, which is then dynamically configured to pass/fail/skip the
line item tests as executed by the module.

There is currently no instantiation of a *unit test* concept for test
modules.  This would not be too difficult to do, basically it would be a
way of running a specific test module against the faux device, without
getting the framework involved. This would improve the developer
experience, I believe. If we think this would be a good idea, then we
should get it on Himawan's radar as work planned. This may be what you were
thinking when you were talking about "subdividing test_aux.sh" -- but, if
so, then you were approaching it from the wrong direction (a unit test is
not a subdivision of an integration test).  There was just a PR that had a
bunch of code in it that might have been doing this -- but if so, then it
was doing it in the wrong way (ad-hoc hacked together for one test module
only).

**Comment by pisuke** [comment]
Thanks Trevor.
What I meant by "can just be configuration files" is that at the moment, as a test developer, I write a config file and run cmd/run -s to generate a report and check all is right.
As you say, introducing unit tests would definitely improve the developer experience and I have the feeling this is what Jonathan was implying.
I will talk about this with Himawan at the next sync then. 
Good to chat about this!

**Comment by grafnu** [comment]
Working on https://github.com/faucetsdn/daq/pull/265

**Comment by grafnu** [comment]
It's not necessarily going to work for everything, but it's good enough for
TLS -- which was my main test case.  I can evolve over time if there's
additional tweaks necessary for supporting other tests.  As per below,
takes ~5s to test TLS (assuming containers are already built), or about 25
sec if there was a change (bin/test_module -b tls tls).

peringknife@peringknife-glaptop3:~/daq$ time bin/test_module tls tls
Configuring OVS bridge daq-bridge-tls
Activating venv
Loading config from local/system.conf into inst/config/system.conf
Launching faux xdhcp tls...
Clensing old container daq-faux-tls
DAQ autoclean docker kill daq-faux-tls
Removing old interface faux-tls
Adding new interface to 110784...
Done with faux device launch.
Capturing fake startup.pcap...
tcpdump: listening on faux-tls, link-type EN10MB (Ethernet), capture size
262144 bytes
3 packets captured
5 packets received by filter
0 packets dropped by kernel
daq-tls
Docker daqf/test_tls daq-tls
7534a77caffe821524d58a9b1716f0957bc0a07e2915d6ad88fe8cdd3968cf81 111025
Configuring test container network...
Removing old interface daq-tls
Adding new interface to 111025...
136: daq-tls@if2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc
noqueue state LOWERLAYERDOWN mode DEFAULT group default qlen 1000
    link/ether de:9c:ac:57:4d:82 brd ff:ff:ff:ff:ff:ff link-netnsid 3
2: eth0@if136: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue
state UP group default qlen 1000
    link/ether 96:9d:90:0a:b4:78 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.20.0.1/16 brd 10.20.255.255 scope global eth0
       valid_lft forever preferred_lft forever


%%%%%%%%%%%%%% Running module command ./test_tls %%%%%%%%%%%%%%%
report:Cipher:
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
Certificate is active for current date.
RESULT pass security.tls.v3
RESULT pass security.x509

Certificate:
[
[
  Version: V1
  Subject: CN=127.0.0.1, OU=Software, O=ExcelRedstone, L=KingsX, ST=London,
C=GB
  Signature Algorithm: SHA256withRSA, OID = 1.2.840.113549.1.1.11

  Key:  Sun RSA public key, 2048 bits
  modulus:
24760626415722235394396036434408410412992357359083324312562580512238875219076070717610785647015580207009886224463812276327017174099935770728650728656740939816974285068337273618599407083896984384857126836325014675367095229818060294119066926552885113615389294676506586778592512738109678028539883163013355653435547148991201609020854771014072024472379346142603603242678273658810840740632078413765961799841123800467855876906712007710470027650473313406390887671106369887446588044220812301651943455718337588036354307793020917417067901760239673500739632049803603350358342630393943345771329862431381880202465803966510388776099
  public exponent: 65537
  Validity: [From: Fri Mar 13 19:49:07 GMT 2020,
               To: Sat Mar 13 19:49:07 GMT 2021]
  Issuer: CN=127.0.0.1, OU=Software, O=ExcelRedstone, L=KingsX, ST=London,
C=GB
  SerialNumber: [    7d980d9c dd4fedab a40076a1 d64d095e 5a101496]

]
  Algorithm: [SHA256withRSA]
  Signature:
0000: 64 B5 60 98 F9 74 26 2E   A7 BF 8E 96 CA 2E 84 EA  d.`..t&.........
0010: 2A EC DD 97 43 B1 0D 38   E3 34 6A 97 BE 2D 63 9B  *...C..8.4j..-c.
0020: EF DA 9D 03 D3 B6 4E 10   60 66 85 B3 E3 67 6E AF  ......N.`f...gn.
0030: F4 80 56 54 41 B6 AD CE   EF 03 2E 13 26 15 EE 14  ..VTA.......&...
0040: 85 18 5F 9D 40 BB 46 F1   F6 71 97 73 68 F0 95 6E  .._.@.F..q.sh..n
0050: 15 14 DE DD BC 6B 26 38   37 65 7C 5F 17 27 E0 F6  .....k&87e._.'..
0060: 56 34 C9 6D B0 6E D0 B4   6E 8E 63 93 9D E0 49 CB  V4.m.n..n.c...I.
0070: 61 F6 D3 D8 1F C2 F3 39   BD DD F8 D4 B1 56 31 E6  a......9.....V1.
0080: 2F 36 5F A2 90 DB D1 04   25 61 F3 3B A1 36 E7 DA  /6_.....%a.;.6..
0090: D1 3A 48 F6 A5 83 18 9C   E1 73 F0 E7 FE 86 78 4F  .:H......s....xO
00A0: 4B C0 61 5B D0 AE 3B E9   7A 8C 5A 65 39 EF B4 01  K.a[..;.z.Ze9...
00B0: A3 4B 02 9B 67 69 41 FD   FF CC EA D8 97 0B 98 FA  .K..giA.........
00C0: C2 DF 3F E6 51 43 68 8A   BD 91 D9 8F 42 DC 97 77  ..?.QCh.....B..w
00D0: 3E 4E F9 F7 0B 34 85 94   9D FF 79 35 44 06 ED 1E  >N...4....y5D...
00E0: 06 0B 4E EE D6 08 CC 27   CA EF 8F 39 D7 C3 E5 12  ..N....'...9....
00F0: 6E 1A E9 46 7F D8 F2 05   F7 05 B2 B2 8E E1 5E C8  n..F..........^.

]

Certificate read successfully
--------------------
Collecting TLS cert from target address %% 10.20.0.5
Cipher:
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
Certificate is active for current date.

Certificate:
[
[
  Version: V1
  Subject: CN=127.0.0.1, OU=Software, O=ExcelRedstone, L=KingsX, ST=London,
C=GB
  Signature Algorithm: SHA256withRSA, OID = 1.2.840.113549.1.1.11

  Key:  Sun RSA public key, 2048 bits
  modulus:
24760626415722235394396036434408410412992357359083324312562580512238875219076070717610785647015580207009886224463812276327017174099935770728650728656740939816974285068337273618599407083896984384857126836325014675367095229818060294119066926552885113615389294676506586778592512738109678028539883163013355653435547148991201609020854771014072024472379346142603603242678273658810840740632078413765961799841123800467855876906712007710470027650473313406390887671106369887446588044220812301651943455718337588036354307793020917417067901760239673500739632049803603350358342630393943345771329862431381880202465803966510388776099
  public exponent: 65537
  Validity: [From: Fri Mar 13 19:49:07 GMT 2020,
               To: Sat Mar 13 19:49:07 GMT 2021]
  Issuer: CN=127.0.0.1, OU=Software, O=ExcelRedstone, L=KingsX, ST=London,
C=GB
  SerialNumber: [    7d980d9c dd4fedab a40076a1 d64d095e 5a101496]

]
  Algorithm: [SHA256withRSA]
  Signature:
0000: 64 B5 60 98 F9 74 26 2E   A7 BF 8E 96 CA 2E 84 EA  d.`..t&.........
0010: 2A EC DD 97 43 B1 0D 38   E3 34 6A 97 BE 2D 63 9B  *...C..8.4j..-c.
0020: EF DA 9D 03 D3 B6 4E 10   60 66 85 B3 E3 67 6E AF  ......N.`f...gn.
0030: F4 80 56 54 41 B6 AD CE   EF 03 2E 13 26 15 EE 14  ..VTA.......&...
0040: 85 18 5F 9D 40 BB 46 F1   F6 71 97 73 68 F0 95 6E  .._.@.F..q.sh..n
0050: 15 14 DE DD BC 6B 26 38   37 65 7C 5F 17 27 E0 F6  .....k&87e._.'..
0060: 56 34 C9 6D B0 6E D0 B4   6E 8E 63 93 9D E0 49 CB  V4.m.n..n.c...I.
0070: 61 F6 D3 D8 1F C2 F3 39   BD DD F8 D4 B1 56 31 E6  a......9.....V1.
0080: 2F 36 5F A2 90 DB D1 04   25 61 F3 3B A1 36 E7 DA  /6_.....%a.;.6..
0090: D1 3A 48 F6 A5 83 18 9C   E1 73 F0 E7 FE 86 78 4F  .:H......s....xO
00A0: 4B C0 61 5B D0 AE 3B E9   7A 8C 5A 65 39 EF B4 01  K.a[..;.z.Ze9...
00B0: A3 4B 02 9B 67 69 41 FD   FF CC EA D8 97 0B 98 FA  .K..giA.........
00C0: C2 DF 3F E6 51 43 68 8A   BD 91 D9 8F 42 DC 97 77  ..?.QCh.....B..w
00D0: 3E 4E F9 F7 0B 34 85 94   9D FF 79 35 44 06 ED 1E  >N...4....y5D...
00E0: 06 0B 4E EE D6 08 CC 27   CA EF 8F 39 D7 C3 E5 12  ..N....'...9....
00F0: 6E 1A E9 46 7F D8 F2 05   F7 05 B2 B2 8E E1 5E C8  n..F..........^.

]

Killed containers daq-tls daq-faux-tls

Module test results:
RESULT pass security.tls.v3
RESULT pass security.x509

real 0m4.681s
user 0m0.759s
sys 0m0.566s

**Comment by jhughesbiot** [comment]
-b option when running the test module isn't supported or at least doesn't work.  

bin/test_module -b tls tls
Activating venv
Loading config from local/system.conf into inst/config/system.conf
Enabling target faux
Enabling target test_-b
Skipping non-enabled daqf/aardvark
Skipping non-enabled daqf/default
Skipping non-enabled daqf/faucet
Build docker/Dockerfile.faux into daqf/faux, log to build/docker_build.faux...
Skipping non-enabled daqf/gauge
Skipping non-enabled daqf/networking
Skipping non-enabled daqf/switch
Skipping non-enabled daqf/test_bacnet
Skipping non-enabled daqf/test_fail
Skipping non-enabled daqf/test_hold
Skipping non-enabled daqf/test_mudgee
Skipping non-enabled daqf/test_pass
Skipping non-enabled daqf/test_ping
Skipping non-enabled daqf/test_brute
Skipping non-enabled daqf/test_discover
Skipping non-enabled daqf/test_nmap
**Could not find specified test module to build: test_-b**

**Comment by grafnu** [comment]
Sorry -- that was a pre-release flag and I ended up swapping it. So,
"build" is the default, and the "-n" option does "no build"  -- going for
default-consistent rather than default-fast.

bin/test_module tls tls should work as well as bin/test_module -n tls tls

Online documentation should be fine -- just my email was old.

**Comment by jhughesbiot** [comment]
Was trying the -b option because it wasn't finding the tls module (even though it was already built).  Found the reason why in the docs.  Thanks.

**Comment by pisuke** [comment]
Closing this issue as addressed by the creation of the test_module script in #265
