### ISSUE TITLE
sed log errors in testing

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/daq#304]
as per [this travis run](https://travis-ci.com/github/henry54809/daq/jobs/299690753#L4324), there's some sed errors appearing in the logs:

    sed: -e expression #8, char 34: Invalid preceding regular expression
    sed: -e expression #8, char 34: Invalid preceding regular expression

looks like a bad sed expression creeped in and should be cleaned up.

**Comment by pisuke** [comment]
OK, noted. Let me have a look.

**Comment by OzyOzk** [comment]
Seems to be caused by the redacted function in test_aux.sh

```
function redact {
    sed -E -e "s/ \{1,\}$//" \
        -e 's/\s*%%.*//' \
        -e 's/[0-9]{4}-.*T.*Z/XXX/' \
        -e 's/[a-zA-Z]{3} [a-zA-Z]{3} [0-9]{1,2} [0-9]{1,2}:[0-9]{1,2}:[0-9]{1,2} [0-9]{4}/XXX/' \
        -e 's/[0-9]{4}-(0|1)[0-9]-(0|1|2|3)[0-9] [0-9]{2}:[0-9]{2}:[0-9]{2}\+00:00/XXX/' \
        -e 's/DAQ version.*//' \
        -e 's/[0-9].[0-9]{2} seconds/XXX/' \
        -e 's/\b(?:\d{1,3}\.){3}\d{1,3}\b/XXX/'
}
```
In the eighth expression there is a non-capturing group (?:\d{1,3}\.){3}\d{1,3} which are not supported by sed.

**Comment by pisuke** [comment]
Thanks @OzyOzk, this regex is intended to replace IP addresses with the XXX string so that the output files can be matched.
Have you already thought of a regex replacement?
Maybe this one could work 
sed -e 's/\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}/XXX/'

**Comment by OzyOzk** [comment]
@pisuke I removed the ?: from statement 8 and tested on various regex testers. It removes the IP as before. I noticed that  before making this change the redacted device reports were all empty.

```
cat docs/device_report.md | redact > out/redacted_docs.md
cat inst/reports/report_9a02571e8f01_*.md | redact > out/redacted_file.md
```

On the above two lines both redacted files were empty as the redact function was failing. So when test_aux compares them to find the difference it was always reporting that there was no difference in the file, giving false positives for all aux tests carried out since this error crept in.

**Comment by pisuke** [comment]
OK @OzyOzk so can you confirm that now the redact function correctly substitutes the IP addresses with XXX and generates non-empty filtered report outputs? If so, please go ahead with this change and complete the integration testing steps on Travis.

**Comment by noursaidi** [comment]
Commit from @grafnu has resolved this issue

```
nour@ubun2:~$ echo "test log ip:999.999.999.999 " | sed -r 's/([0-9]{1,3}\.){3}[0-9]{1,3}/X.X.X.X/'
test log ip:X.X.X.X
nour@ubun2:~$ echo "127.0.0.1 " | sed -r 's/([0-9]{1,3}\.){3}[0-9]{1,3}/X.X.X.X/'
X.X.X.X
nour@ubun2:~$ echo "1000.1000.1000.1000 " | sed -r 's/([0-9]{1,3}\.){3}[0-9]{1,3}/X.X.X.X/'
1000.1000.1000.1000
nour@ubun2:~$ echo "1.2.3.4.5" | sed -r 's/([0-9]{1,3}\.){3}[0-9]{1,3}/X.X.X.X/'
X.X.X.X.5
```
