### ISSUE TITLE
Suggestion:Reporting

### ISSUE THREAD

**Issue by ewRedstone** [faucetsdn/daq#33]
- Report to include how far along sequence before aborted.
- Report to include exception as to why sequence aborted.
- Report should be generated regardless of whether device failed or not.
- If device fails old report is left behind from previous test.

**Comment by pisuke** [comment]
The topic of increased verbosity in reports deserves more discussion and alignment in line with the requirements of project reporting and test approval.

At the moment the report output is minimal:

DAQ scan report for device 38:d1:35:02:00:50

############# Report for test nmap
22/open/tcp//ssh///,
53/open/tcp//domain///,
80/open/tcp//http///,
139/open/tcp//netbios-ssn///,
443/open/tcp//https///,
445/open/tcp//microsoft-ds///

############# Report for test brute
Target port 10000 not open.

############# Report complete.

To enable better tracking of the tests the report should include also in the output text the following:

- device make / device manufacturer / firmware version in addition to MAC address (these should be provided manually by the end user in a configuration text file)
- date (the date is on the filename but should be also in the report text) 
- a description of the test (this could come from a user provided configuration file that is project related) to enable the project management audience to understand what the test is about
- cross reference to a test number/name/ID that is usually included in aproject management spreadsheet - this can be also in a configuration file together with the description
- reporting the outcome of each test with a pass/fail record and a log showing the results of each sub-test; the level of verbosity needs to be right to be useful to the testing engineer and to the project management audience

**Comment by grafnu** [comment]
Thanks -- need to break this down into smaller chunks. All this stuff is
good, but it's really at least three different things: 1) device config
file, 2) small improvements (date), 3) reporting outcome.

**Comment by pisuke** [comment]
Thanks, I've split this suggestion/feature request into three:

device config file: https://github.com/faucetsdn/daq/issues/72
small improvements: https://github.com/faucetsdn/daq/issues/73
reporting outcome: let's continue tracking this issue for the remaining points.
