### ISSUE TITLE
Validate connection.min_send

### ISSUE THREAD

**Issue by spectre-storm** [faucetsdn/daq#336]

**Comment by noursaidi** [comment]
@pisuke @em-redstone , only comment on this test is that the report appendix states that "Device sends data at a frequency of less than 5 minutes", I think this should be more general as the test depends on the monitor_scan which is configurable within DAQ, and may not necessarily be 5 minutes.

**Comment by pisuke** [comment]
@noursaidi @spectre-storm @em-redstone the best way would be to add a parameter in the module_config.json to be used by the test for the configuration of the monitoring time.
I think we need to discuss this with Trevor.

**Comment by pisuke** [comment]
Addressed in #498
