### ISSUE TITLE
Validate communication.type.broadcast

### ISSUE THREAD

**Issue by spectre-storm** [faucetsdn/daq#337]

**Comment by pisuke** [comment]
@noursaidi this test is intended to be informative and fromthe monitor.pcap report the number of unicast, multicast and broadcast messages in a table.
Can you please confirm this is the implemented behaviour with a test run?

**Comment by noursaidi** [comment]
@pisuke test currently only reports the types of broadcast packets received, not the numbers.

The number of packets is counted, so appears to just be a case of appending it to the report appendix.

**Comment by noursaidi** [comment]
@pisuke I've created issue #434 to add the number of packets received into the report.

@em-redstone the test currently counts all broadcast messages going in or out, I think it need to be restricted so it only coming from the device. There is a tcpdump parameter "-Q in" which could be used.

**Comment by noursaidi** [comment]
@em-redstone I've added the number of packets and fixed a few bugs in this test (#439) - All that is outstanding is the test needs to distinguish between broadcast and multicast packets and report these separately.

**Comment by em-redstone** [comment]
Thanks @noursaidi, 

I should be able to start working on this soon, is there somewhere in DAQ which allows you to configure it to send multicast packets? Similar to how dhcp lease time can be configured?

Regards.

**Comment by grafnu** [comment]
What do you mean "DAQ to send multicast packets" -- what, exactly, do you
want sending the packets?  "DAQ" is a comprehensive framework of stuff, so
it consists of many parts.  THere's the faux device, networking container,
etc... ?  There's currently nothing that deals with multicast, so the short
answer will be "no"...

**Comment by em-redstone** [comment]
Thanks for the quick reply Trevor, I was wondering if there was a way to configure DAQ to send multicast packets in some way to the faux devices, so I can test out the multicast changes (when added) to the broadcast test within daq (Similar to how dhcp_long can be tested with the dhcp lease config)

Regards.

**Comment by noursaidi** [comment]
@grafnu @em-redstone 
The test description as @pisuke mentioned is for the test to check and report the types/number of packets the device sends. I think therefore all needs doing is to extend the current test which uses the monitor.pcap packet dump to look for broadcast and unicast to also look for any multicast packets a device may send while under test. I don't think whether or the device supports multicast is outside the scope of this test, therefore it shouldn't need to configure DAQ to do anything special for this.

I also believe there's built in to tcpdump already filter for multicast, so it should be simple, although I think multi cast packets also come up under the broadcast filter, so you might need to do "BROADCAST NOT MULTICAST" and vice versa.

**Comment by em-redstone** [comment]
Thanks @noursaidi, I'll have a look. I was looking for a way to test out the updated tcpdump command changes in some way (whether in daq or not) before pushing it to my repo. I guess i can just write some scripts outside of daq to test the tcpdump command for now.

Many thanks.

**Comment by grafnu** [comment]
I don't understand what you mean by the comparison to dhcp_long -- my guess
is that's not the right example to use since it's very different from
anything multicast does. DHCP responds to requests from the device, it
doesn't proactively send any traffic.

If you need multicast traffic, why can't you just send some to the DUT from
the test module container?  That's what the system does for BacNET
discovery, for example.

**Comment by spectre-storm** [comment]
Em-redstone to share the code with Arup

**Comment by em-redstone** [comment]
Hi @pisuke, @noursaidi and all,

Good evening, I've pushed the latest code for the broadcast test in my repo:

https://github.com/em-redstone/daq/tree/issue337-multicastnetworktest

The broadcast test now checks for multicast packets (all packets which have IP addresses within the range 224.0.0.0 to 239.255.255.255). 

This was tested by running the script, and the tcpdump commands themselves on my machine against ping packets, and also a small script which would send out UDP multicast packets.

Running the changes through to travis now.

Please take a look, and let me know how it goes.

Many thanks.
