### ISSUE TITLE
Validate protocol.app_min_send

### ISSUE THREAD

**Issue by spectre-storm** [faucetsdn/daq#338]

**Comment by noursaidi** [comment]
@pisuke , @em-redstone I've taken a look at this test and a few points.

The code shows an "Infrastructure Excludes JSON file" functionality which appears to be currently disabled (?) - I think this needed for this test to be validated. For example, from one device I only had NTP packets and the device passed, not sure this is reflective of the test intent.

Configuration information generally needed and readme file

The report appendix states that "Device sends data at a frequency of less than 5 minutes", I think this should be more general as the test depends on the monitor_scan which is configurable within DAQ, and may not necessarily be 5 minutes.

**Comment by pisuke** [comment]
@noursaidi I think this test should be removed as it currently is not in the test plan.
@spectre-storm what do you think? If you'd like to keep it, it needs some adjustments as the definition is not completely clear and the implementation doesn't do what the test is supposed to.

**Comment by spectre-storm** [comment]
If it's not in the test plan, we should remove it

**Comment by noursaidi** [comment]
Deprecated test removed as a part of network module clean up. PR #565 merged
