### ISSUE TITLE
Validate network.ntp.support

### ISSUE THREAD

**Issue by spectre-storm** [faucetsdn/daq#339]

**Comment by noursaidi** [comment]
@pisuke I've validated this this test and I'm happy the test requirements are met

**Comment by noursaidi** [comment]
@pisuke the test should now incorporate a check on the NTP version to ensure it is NTPv4. This should be possible by examining the packets which report the protocol version

**Comment by noursaidi** [comment]
PR #487 implementing ntpv4 check merged
