### ISSUE TITLE
DAQ hanging on INFO:runner:Entering main event loop.

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#35]
Sometimes the system becomes unstable and hangs at the “INFO:runner:Entering main event loop.” stage. 
In order to make it work again it is necessary to restart the VM / computer or to unplug/plug the adapter so that the kernel restarts the adapter.

**Comment by grafnu** [comment]
The most recent version has some additional diagnostic output/instructions right after the "Entering main event loop" output, so next time this happens, please take a look and update this issue with the relevant output, thanks!

**Comment by pisuke** [comment]
I'm closing this issue since it is related to OS system networking instability on virtual machines.
