### ISSUE TITLE
Confirm Cisco Switch Configuration for DAQ testing

### ISSUE THREAD

**Issue by spectre-storm** [faucetsdn/daq#365]
Jonathan's suggestion for Cisco switch config https://docs.google.com/document/d/1LS5N41MAjGD-9ycbLm3Ug6cLMZADZ-zf_gZTbFPsuuE/edit?ts=5e95cf61

Need confirmation for those config.

**Comment by pisuke** [comment]
@spectre-storm @jhughesbiot I've included my comments in the document.

**Comment by spectre-storm** [comment]
Pisuke will create cisco config file under /etc
