### ISSUE TITLE
startup.pcap empty

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#37]
I'm running DAQ in local mode and the startup.pcap file generated by DAQ is empty.

Also, another thing related is that the location of the pcap files is no longer inst/run-port-01/nodes/gw01/tmp/startup.pcap as reported in the [example](https://www.google.com/url?q=https://github.com/grafnu/daq/blob/master/docs/startup_pcap.md&source=gmail&ust=1540387986782000&usg=AFQjCNHa0yHlsIKhtRQ2jSRyH4eeRoCXAQ), but something like inst/run-port-01/scans/startup.pcap.

**Comment by grafnu** [comment]
Addressed in https://github.com/grafnu/daq/pull/28
