### ISSUE TITLE
pics test has misleading error

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/daq#386]
When there's a network failure of some kind and BacNET discover fails and can't reach the target device, the bacnet pic test reports that "the pics file could not be found" rather than "the device discovery failed" -- which is misleading (because the pics file is perfectly fine/available).

**Comment by pisuke** [comment]
Thanks @grafnu noted and added on the project Kanban.

**Comment by noursaidi** [comment]
I think the BACnet discover is succeeding, the logs show that a BACnet device is found. The test also won't check for a picsfile if a BACnet device isnt found. I think the test reporting needs to be updated with an additional case for this scenario

What seems to be happening though is that for some bizarre reason, and seemingly only on port 02 in the aux tests, is the pics.csv isn't' being copied to or linked to within the container. The test logs show
`ls: cannot access '/config/type/': No such file or directory`

Looking inside the containers, it finds its way to 01 and 03, but not 02
```nour@ubun2:~/daq-working/daq/docker$ sudo docker exec -it daq-bacext01 /bin/bash
root@bacext01:~# ls -la /config/type
total 40
drwxr-xr-x 2 root 1000  4096 May  1 22:17 .
drwxr-xr-x 6 root root  4096 May  2 20:09 ..
-rw-r--r-- 1 root 1000   184 May  1 22:17 lizard.txt
-rw-r--r-- 1 root 1000 26386 May  1 22:17 pics.csv
root@bacext01:~# exit
exit
nour@ubun2:~/daq-working/daq/docker$ sudo docker exec -it daq-bacext02 /bin/bash
root@bacext02:~# ls -la /config/type                                                                                                                                                                       
ls: cannot access '/config/type': No such file or directory
root@bacext02:~# exit
exit
nour@ubun2:~/daq-working/daq/docker$ sudo docker exec -it daq-bacext03 /bin/bash
root@bacext03:~# ls -la /config/type
total 40
drwxr-xr-x 2 root 1000  4096 May  1 22:17 .
drwxr-xr-x 6 root root  4096 May  2 14:35 ..
-rw-r--r-- 1 root 1000   184 May  1 22:17 lizard.txt
-rw-r--r-- 1 root 1000 26386 May  1 22:17 pics.csv
root@bacext03:~# exit
exit```

**Comment by grafnu** [comment]
Sorry -- seems I have my details confused. The error is still "misleading"
-- but it's the case when the device *is* found.  The file is not there for
02 is intended exactly to check this case.  The problem then is that the
error is still inconsistent in the two "device" cases (found and not found)

See the logs https://travis-ci.org/github/grafnu/daq/jobs/682195817#L8742 --
the device is not found, but the logs show an error "cat:
tmp/BacnetPICSTest_APPENDIX.txt: No such file or directory" and then don't
have any RESULT line.

**Comment by pisuke** [comment]
@grafnu @noursaidi do the pass/fail/cases described in this new [`readme.md`](https://github.com/pisuke/daq/blob/451c5113de915ddb49b84d7d267817e3589a5126/subset/bacnet/readme.md) file describing the `test_bacext`  module give a reasonable description of how the test would behave?

**Comment by grafnu** [comment]
For protocol.bacnet.version is there a case where it is a bacnet device but
the protocol version fails for some reason?  E.g., maybe the system is
misconfigured?

For the pics -- question is if providing a BACnet device without a PIC
statement is allowed.  Or if you supply a PIC statement but there is no
bacnet device.

Either way seems fine to me, we might just want to clarify.

My point with the "inconsistent error" wasn't that the pass/fail/skip case
was incorrect, but that the error "detail" field was misleading.

**Comment by noursaidi** [comment]
@pisuke I've put a pull request #404 to correct the issue. The possible report outputs are as follows. Currently there is no check for a pics.csv file if a Bacnet device is not found, should this be incorporated as an additional case?

| Bacnet | Pics | Pass/Fail | Report Output
| --- | --- | --- | --- |
| Yes | Yes | Pass | Pass|
| Yes | Yes | Fail | Fail|
| Yes | No | Skip | Bacnet device found but pics.csv not found in device type directory.|
| No | (no check) | Skip | Bacnet device not found... Pics check cannot be performed.  |

**Comment by grafnu** [comment]
I think it would be great if the table was complete and the case of "pics
defined but no device found" would be indicated... possibly as a fail.  The
reason being that somebody should only define a pics statement when there's
an expectation that there's a bacnet device... so under what "normal"
circumstances would there be pics but no device?  Better to surface the
error rather than hide it.

**Comment by noursaidi** [comment]
I agree, I've made the changes and updated the readme.md to incorporate the following. conditions. The possible outputs look as follows.

| Bacnet | Pics | Pass/Fail | Report Output
| --- | --- | --- | --- |
| Yes | Yes | Pass | The devices matches the PICS|
| Yes | Yes | Fail | The device does not match the PICS |
| Yes | No | Skip | BACnet device found, but pics.csv not found in device type directory. |
| No | Yes | Fail | PICS file defined however a BACnet device was not found. |
| No | No | Skip | BACnet device not found and pics.csv not found in device type directory. |

Additionally when theres an error (typically time out during connection to BACnet device), the test will fail and the error will appear in the report (e.g. Error encountered during test - Timeout while waiting for response for id 0)

@pisuke do you agree with these test outputs? I'm having issues with my branch so will put another pull request in

**Comment by grafnu** [comment]
@noursaidi  -- thanks for pulling all that together... looks great!  When you say "I'm having issues with my branch", what do you mean, exactly?  I'd prefer not putting another pull request in just because a branch is messed up... you can reset your branch to whatever files you want. The problem with just doing a new pull request is that it loses any history. 

If you need to reset your branch, you can just do a "git reset master" and then commit the changes, and all the files will stay the same and can use the same pull request after you do a force-push to your branch.

**Comment by noursaidi** [comment]
Thanks @grafnu , I've resolved my issue and marked you as a reviewer for the existing PR #404 

My issue was merge conflicts which didn't make sense to me after I used a separate branch to avoid polluting the commit history and additional Travis CI runs on the master daq repo whenever I pushed changes back to my repo
