### ISSUE TITLE
Travis fails on fresh master pull on personal fork

### ISSUE THREAD

**Issue by em-redstone** [faucetsdn/daq#456]
Hi all,

I would like to submit a pull request but I'm having trouble with travis at the moment as it has been a while since I last travis tested - I'm not sure if I'm missing a few steps in integration testing now, but I am receiving multiple failed travis tests even on a freshly pulled master branch...

Github repository:
https://github.com/em-redstone/daq

Travis:
https://travis-ci.com/github/em-redstone/daq/builds/168765797

Any suggestions would be appreciated, many thanks!

**Comment by noursaidi** [comment]
Hi @em-redstone 

I've had that a lot with every version, you need to fetch the tags and push them by including '--tags'. For me the following usually does the job if I recall correctly.
```
git fetch upstream --tags
git push --tags
```

**Comment by grafnu** [comment]
Correct -- the relevant bit in the logs is below.  Unfortunately there's no
easy way to automate this using git... it's just the way git works (tags
are separate from branches).  If it works for you locally but not on
travis, then it's possibly you already have the tags locally, so you'd just
need to do "git push --tags"... You can also try "git describe" to see if
it does something sane.

fatal: ambiguous argument '1.4.1': unknown revision or path not in the
working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Tagged version 1.4.1 not found.
Maybe you need to fetch tags: git fetch --tags

**Comment by em-redstone** [comment]
Thanks very much guys, it resolved the issue, closing now.
