### ISSUE TITLE
local/system.conf - More generic options

### ISSUE THREAD

**Issue by MPH13** [faucetsdn/daq#52]
Have more generic options in the local/system.conf such as intf_names=

This is to provide a generic subset of options so the user can see what a standard system configuration file would look like. This could include both options for a single device and also a switch but simply have them commented out so it's not as expansive as some of the templates in the misc/ directory.

**Comment by grafnu** [comment]
I'm not sure what you mean, can you clarify?  There is no
"local/system.conf" file in the repo -- that's local configuration so it's
not possible to have something specific there.   How is what you're
suggesting different than the misc/system_*.conf examples?

**Comment by MPH13** [comment]
The reason for submitting this issue is that there was no intf_names in the local/system.conf originally. I know it's created at the time of running part of the setup, but it's created from a template I believe (not sure). This was causing major difficulty for me when first trying to run cmd/run -s because there was nothing in the local/system.conf to let me know there was an option for interface names. You have to read through the large amount of options in the misc/system.conf template to see ALL the available options.

I'm stating that there could possibly be a more generic set of options loaded into the local/system.conf so that you can more quickly and easily adjust it without having to add or subtract items that are referenced in the misc/system.conf template file. Eg. comment them out, but being able to see them could possibly help.

**Comment by grafnu** [comment]
local/system.conf should be initially populated with misc/system_base.conf
-- if you remove/move your current local/system.conf file and run again it
should populate with the clean defaults. Then, frame any specific
suggestions on what should be there... There is an intf_names entry in that
file.   (If there's not, then there's something else bad going on because
there should be.)

**Comment by MPH13** [comment]
All you have mentioned above is correct.

I performed the following for testing:
-Removed local/system.conf
-Ran cmd/run -s
-local/system.conf was recreated exactly from misc/system_base.conf 

I feel it was not this way when I originally tested, but is proven true. Will close this issue.

**Comment by grafnu** [comment]
It was, in fact, changed recently so it very may well have been different
before. The joys of working with a work-in-progress setup.
