### ISSUE TITLE
Enumerate expected exposed ports in device configuration file

### ISSUE THREAD

**Issue by ewRedstone** [faucetsdn/daq#60]
It would be nice for Daq to have a  common data store that tests are able to read and write from.

This may trigger additional features in further tests.

i.e. results of nmap scan would then feed into the brute test, that would then enable brute force tests on those ports and protcols found.

**Comment by grafnu** [comment]
Understood about the use case, but unlikely to be a common data store. What's needed is an if-then capability with parameters. Directly exposing a data-store breaks encapsulation.

**Comment by grafnu** [comment]
Would like to identify an exact use-case where this is desirable.  The example of "should run brute or not" I think it better handled through explicit configuration, not dynamic adjustment.

I realized there are provisions for doing this already, but I wouldn't want it to be used unless it was demonstrably the right thing to do.

**Comment by pisuke** [comment]
The idea of conditional tests sounds good in this specific instance.
I think that the sequence of operations could be:
nmap scans ports
for each port that is open, execute brute test on that port using the relevant protocol(s)
save output log and test results to report

I think that the data store could be useful though for storing results of soak tests and let a soak test module parse them and create a "cumulative" report.
But this can also be done perhaps by adding a docker bind mount to the inst/ folder? Any problem with any of these approaches?

**Comment by grafnu** [comment]
All exposed ports should be explicitly listed in the device config file
(when I create that) -- I don't see why it needs to be conditional on port
scan.  Similarly, the port scan should fail if it discovers an open port
that's not explicitly listed. Really, this issue should then be "need a way
to figure out which ports to run brute test on" -- not presuming a solution
(shared config).

Soak test handling is another issue, so should separate that out since it's
a totally different use case and don't want to presume the same solution.

**Comment by pisuke** [comment]
OK, thanks Trevor. So shall we say this can be closed by acknowledging the appropriate action is to add support for a device configuration file that has test configuration options?

**Comment by grafnu** [comment]
I updated the title to reflect the desired work -- we can keep this issue open. 

Summary: I will implement the capability to explicitly specify exposed ports for a device, and that device configuration can then be used to guide which ports are probed by a given test.

**Comment by pisuke** [comment]
I've moved this issue to the pressing items, noting we're targeting completing the brute module soon.
The understanding is that this will be implemented as an additional per-device configuration file in the daq/misc/test_site/mac_addrs/9a02571e8f01/ folder, or similar folder.

**Comment by grafnu** [comment]
Fixed/enabled/demonstrated in https://github.com/grafnu/daq/pull/123
