### ISSUE TITLE
local/system.conf host_tests variable parsing

### ISSUE THREAD

**Issue by ewRedstone** [faucetsdn/daq#68]
When using the local/system.conf host_tests variable it would appear that the parsing of local/local_tests.conf file isnt correct as notifed after using command cmd/build in terminal message:> No such file or directoryst_tests.conf

local/system.conf
host_tests=local/local_tests.conf

local/local_tests.conf
include misc/host_tests.conf

The workaround for now is to manipulate tests through misc/host_tests.conf

**Comment by grafnu** [comment]
I'm having trouble reproducing and/or don't understand the
problem/question.  Se output below -- same logic, but I've added a few
extra debugging lines (which I'll push upstream as part of this fix).  What
part of the output below isn't working for you?  If you include the exact
output from when you run the command (like I did below), it might be more
illustrative.

~/daq$ *fgrep host_tests local/system.conf*
host_tests=local/local_tests.conf
~/daq$ *fgrep host_tests local/local_tests.conf*
include misc/host_tests.conf
~/daq$ *cmd/build*
Loading config from local/system.conf...
Including tests from *local/local_tests.conf*
Including tests from *misc/host_tests.conf*
Including build files from docker
Including tests from subset/pentests/pentests.conf
Including build files from subset/pentests
Build docker/Dockerfile.aardvark into daq/aardvark, log to
build/docker_build.aardvark...

**Comment by ewRedstone** [comment]
I fixed this myself by re-copying the file misc/host_tests.conf > local/local_tests.conf.

Seemingly the original cause is the line endings got messed up and the parser is perhaps only parsing by LF

**Comment by grafnu** [comment]
Line endings have been a problem in the past, yes.  Somewhere something
injects windows-style endings which can cause a real problem in multiple
parts of the system!

**Comment by grafnu** [comment]
Closing for now. Re-open or file a new request if this is a persistent problem, then we'll need to track-down the source of said line-endings.
