### ISSUE TITLE
Ping test is failing to physical open flow switch over control plane

### ISSUE THREAD

**Issue by ewRedstone** [faucetsdn/daq#69]
Ping test is failing from test switch interrogation docker container to switch over control plane.

Suspect routing between docker container and switch control plane is at fault.

Even though the startup_cmds=misc/startup_phy.cmd is defined and the bin/physical_sec is running and is able to ping the switch. You can see this working as part of the inst/cmdrun.log

**Comment by ewRedstone** [comment]
Ping test works when daq is in a faux environment

**Comment by ewRedstone** [comment]
Ping test fails in a real world environment with physical devices

**Comment by grafnu** [comment]
Problem was due to an overly complex configuration mechanism, and bad documentation. Both fixed now.

1. Should work with your current config setup.
2. No longer necessary to have the specific startup_cmds entry (although it shouldn't cause any problems)

Please update to latest and try again.
