### ISSUE TITLE
Suggestion: device config file

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#72]
Add a device config file input by the tester/end user that contains device make / device manufacturer / firmware version in addition to MAC address (these should be provided manually by the end user in a configuration text file).

Possibly, this information can also be derived programmatically via nmap scripts like this one.
https://github.com/nmap/nmap/blob/master/scripts/bacnet-info.nse

**Comment by grafnu** [comment]
Fixed in https://github.com/grafnu/daq/pull/92
