### ISSUE TITLE
Merge changes from forked wiki repo

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#75]
I understand that the following should work to merge changes from the following forked wiki repo
[https://github.com/pisuke/daq.wiki.git](https://github.com/pisuke/daq.wiki.git)
according to the instruction provided at this [link](https://gist.github.com/larrybotha/10650410).

The owner of the original repo (https://github.com/faucetsdn/daq.wiki.git) should do the following.

```
$ git clone https://github.com/faucetsdn/daq.wiki.git
$ cd https://github.com/faucetsdn/daq.wiki.git

# squashing all forked repo changes
$ git pull https://github.com/pisuke/daq.wiki.git master

$ git push origin master
```

**Comment by grafnu** [comment]
Published https://github.com/faucetsdn/daq/wiki

The hardest part of this, of course, was figuring out how to authenticate when I pushed!
