### ISSUE TITLE
DHCP short lease test

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#83]
Implement a subtest of the dhcp module (suggested name dhcp.shortlease), where DAQ sets initially a 1 minute lease and then checks that the device re-requests DHCP after 1 min. Then DAQ sets a long term lease and starts the next tests.

**Comment by grafnu** [comment]
Waiting for review of PR, then this will be an issue for test development, not the framework.

**Comment by pisuke** [comment]
@ewRedstone can you please check code and approve review so that Trevor can merge the code of the DHCP timeout and scan result?
This will then need a little bit of test dev that we can discuss next Tuesday. Thanks!
