### ISSUE TITLE
Provide a way to hierarchically name tests

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#84]
This feature request is about enabling hierarchical naming of tests, for instance switch.port.link

**Comment by grafnu** [comment]
Need to know what the use case is. Three are multiple names in the system, so I need to know specifically what you want to achieve -- e.g. show up in a report, for filtering test execution.

**Comment by pisuke** [comment]
The main use cases I can think of now are:
1. selecting/deselecting tests and sub tests (test filtering)
2. showing the name of the test and subtests in the reports
3. grouping tests according to test domain to enable code reuse
4. rationalising the tests classification (not much to do with programming, but still useful!)

**Comment by grafnu** [comment]
Addressed in https://github.com/grafnu/daq/pull/108
