### ISSUE TITLE
Provide the capability to select tests and sub-tests per device via console

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#85]
The end user of DAQ should be able to select / unselect tests and subtests in a file inside the /local folder.
I understand that at the moment this is provided in misc/host_tests.conf as a blanket setting but it would be useful to have it on a per-device basis.

**Comment by grafnu** [comment]
In order for this to be considered "Urgent" I need a sense of exactly what it is that's being blocked, and what can't be done without it. An "urgent request" basically means "stop other things and maybe take some shortcuts to get it fixed" so it should not be used without clear justification.

**Comment by pisuke** [comment]
We're approaching the phase where automated tests on different devices will be needed and this mechanism will allow the end user to just plug and unplug devices, after having created different configuration files for them. The key reason is that when two devices having different sets of test requirements (for instance PoE vs non-PoE) are tested, the testing can happen in parallel without showing failures.
Personally a useful use case is avoiding to have to tinker with test files multiple time and having to restart DAQ to change the test configuration for a different device.
I understand that this was prioritised by Kathy in conjunction to one of the projects and to the UI discussions.

**Comment by grafnu** [comment]
https://github.com/grafnu/daq/pull/130
