### ISSUE TITLE
Include output of all tests and subtests in reports

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#86]
It is required for all the selected tests to have an output in the report, which must show the pass / fail state and relevant information from the test log.

**Comment by grafnu** [comment]
How is this different than the current behavior?

It is up to each test to determine what is shown in the report, "relevant
information" is test-dependent.  Something like the "fail" will never have
any relevant information, so would never be shown.

Maybe need to identify a more specific use case that currently does not
work and then we can identify the proper fix.

**Comment by pisuke** [comment]
The use case for this issue is that the full output of each test must be shown in the report for project managers and designers to approve. 
Here is a suggested structure of the report.

Device identification (device name, device mac address, from configuration file edited by user)
Device description (from configuration file edited by user)
Report date

Report summary 
(table of all tests and subtests and indication of whether they pass - PASS - or fail - FAIL - ) 

Then for each test:
Test description (from configuration file edited by the test software developer)
Test pass/fail (automation score/exit code)
Test output details (full log of test)

For tests running for longer amount of times (soak tests), the results will be the one of the last test + the results of the soak tests themselves.

Each test must output its results to the report.

**Comment by grafnu** [comment]
K -- this is helpful as an overall outline.  Once we have a concrete
specific example we can iterate to see what needs tweaking.

**Comment by grafnu** [comment]
Addressed in https://github.com/grafnu/daq/pull/108
